create table if not exists public.experience
(
    company_name varchar,
    id           integer generated by default as identity,
    description  varchar,
    start_date   date,
    end_date     date,
    position     varchar
);

alter table public.experience
    owner to postgres;

create table if not exists public.skill
(
    id         integer generated by default as identity,
    skill_name varchar not null,
    "desc"     varchar
);

alter table public.skill
    owner to postgres;

create table if not exists public.summary
(
    id                         integer generated by default as identity,
    roles_and_responsibilities varchar not null
);

alter table public.summary
    owner to postgres;

